package com.MACU.BUI;

import org.openqa.selenium.By;

import com.MACU.framework.BaseClass;

public class CreateNewArticleFlow_POM extends BaseClass{

	
	//MACU_BUI
	        public static By byNavigationButton                   = By.id("navigationSetBtn");
			public static By byClickHomeButtonXpath               = By.xpath("(//div[text()='Home']//a)");
			public static By byClickContentButtonXpath            = By.xpath("(//div[@class='navigation-item']//span[text()='Contacts'])[1]");
			public static By byEnterUserNameXpath                 = By.xpath("//input[@automationid='Name']");
			public static By byEnterUserEmailIDXpath              = By.xpath("//input[@automationid='All Email Addresses']");
			public static By byClickSearchButtonXpath             = By.xpath("//span[text()='Search']");
			public static By byClickSearchResultXpath             = By.xpath("//span[text()='User']");	
			public static By byClickSummaryButtonXpath            = By.xpath("//span[text()='Summary']");
			public static By byClickAddButtonXpath                = By.xpath("//span[text()='Add']");
			public static By byClickEditButtonXpath               = By.xpath("//span[text()='Edit']");
			public static By bySelectExistingRolepath             = By.xpath("//div[@id='SlaViewerViewModel']//div[@class='oj-dialog-content oj-dialog-default-content']//div[@class='sla-viewer']//div[@class='oj-flex-bar']//table[@automationid='slaInstances']//tbody//tr");
			public static By byClickAddNewButtonXpath             = By.xpath("//div[@id='SlaViewerViewModel']//div[@class='oj-dialog-content oj-dialog-default-content']//div[@class='sla-viewer']//button//span[text()='Add New']");
			public static By byClickDisableButtonXpath            = By.xpath("//div[@id='SlaViewerViewModel']//div[@class='oj-dialog-content oj-dialog-default-content']//div[@class='sla-viewer']//button//span[text()='Disable']");
			public static By byClickDisableOKButtonXpath          = By.xpath("//div[@class='oj-flex oj-sm-flex-direction-column dialogNoWrap oj-dialog oj-component dialogBody oj-component-initnode oj-draggable']//span[text()='OK']");
			public static By byClickSLADropDownButtonXpath        = By.xpath("//div[@id='AddSlaInstanceDialogViewModel']//div[@class='menu-container']//input[@class='select-box-input']");
			public static By byClickSLADropDownOKButtonXpath      = By.xpath("//div[@id='AddSlaInstanceDialogViewModel']//div[@class='oj-dialog-footer dialogFooter']//span//button//span[text()='OK']");
			public static By byClickUserProfileOKButtonXpath      = By.xpath("//div[@id='SlaViewerViewModel']//div[@class='oj-dialog-footer dialogFooter']//span//button//span[text()='OK']");
			public static By byClickUserProfileSaveAndCloseXpath  = By.xpath("//div[@class='ws-toolbar-button-image bui-icon save-close-icon fa-lg']");
			public static By byClickContactsCloseButtonXpath      = By.xpath("//a[@class='closeButton']//i");
			public static By byClickAppClickHereXpath             = By.xpath("//a[text()='Click here']");
			public static By byClickCloseActionCenterXpath        = By.xpath("//div[@id='landingPanel-notifications']//button[@class='oj-button oj-button-half-chrome mobile-close-icon mobile-close-button closeFoldout']//label[text()='Close Action Center']");
			public static By byClickCongurationButtonXpath        = By.xpath("//div[@automationid='Configuration_Service']");
			public static By byConfigurationXpath				  = By.xpath("//div[@automationid='Configuration']");
			public static By byClickServiceButtonXpath            = By.xpath("//div[text()='Service']");
			public static By byClickKnowledgeAdvancedButtonXpath  = By.xpath("//div[text()='Knowledge Advanced']");
			public static By byClickAuthoringButtonXpath          = By.xpath("//span[text()='Authoring']");
			public static By byClickMainTasksButtonXpath          = By.xpath("//div[@id='rntab']//ul//li[@testidentifier='MainNavBar_Tasks']//a");
			public static By byClickMainContentButtonXpath        = By.xpath("//div[@id='rntab']//ul//li[@testidentifier='MainNavBar_Content']//a");
			//public static By byClickMainContentButtonXpath        = By.xpath("//div[@id='rntab']/ul/li[2]");
			public static By byClickAddArticleButtonXpath         = By.xpath("//div[text()='Process']//following-sibling::a[@testidentifier='ContentNavBar_Add_Process']");
			public static By byEnterTitleNameFieldXpath           = By.xpath("//input[@testidentifier='Content_ContentType_Add_SUMMARY']");
			public static By byEnterKeyWordNameFieldXpath         = By.xpath("//input[@testidentifier='Content_ContentType_Add_KEYWORD']");
			public static By byClickImageFieldXpath               = By.xpath("(//a[@class='cke_button cke_button__image cke_button_off'])[1]");
			public static By byClickBrowserImageFieldXpath        = By.xpath("(//span[text()='Browse Server'])[1]");
			public static By bySelectBrowserImageFieldXpath       = By.xpath("//a[text()='MACU_VIEW']");
			public static By bySelectImageXpath                   = By.xpath("(//div[@class='files_thumbnails fake no_list']//a)[1]");
			public static By byPopUPWindowXpath                   = By.xpath("//table//span[text()='OK']");
			public static By byScrollToContentInfoXpath           = By.xpath("(//span[text()='Contact Info'])[1]");		
			public static By byContantWindowXpath                 = By.xpath("((//span[@class='cke_bottom cke_reset_all'])[2]//preceding-sibling::*)[2]");
			public static By byEnterContentInfoXpath              = By.xpath("//body[@class='cke_editable cke_editable_themed cke_contents_ltr cke_show_borders']");
			public static By byContantInfoWindowXpath             = By.xpath("((//span[@class='cke_bottom cke_reset_all'])[1]//preceding-sibling::*)[2]");
			public static By byScrollToImageXpath                 = By.xpath("(//span[text()='Image'])[3]");
			public static By byClickImageXpath                    = By.xpath("(//a[@class='cke_button cke_button__image cke_button_off'])[3]");
			public static By byScrollToJumpTOXpath                = By.xpath("//span[text()='Jump To']");
			public static By byClickLinkXpath                     = By.xpath("(//span[@class='cke_button_icon cke_button__addarticlelink_icon'])[4]");
			public static By byEnterInputValueLinkXpath           = By.xpath("((//div[@class='cke_dialog_body']//table[@class='cke_dialog_contents'])[2]//input[@class='cke_dialog_ui_input_text'])[1]");
			public static By byEnterInputValueXpath               = By.xpath("((//div[@class='cke_dialog_body']//table[@class='cke_dialog_contents'])[2]//input[@class='cke_dialog_ui_input_text'])[3]");
			public static By byEnterInputLinkValueXpath           = By.xpath("(//div[text()='Article Link']//following::input)[3]");
			public static By byEnterInputLinkNameXpath            = By.xpath("(//div[text()='Article Link']//following::input)[5]");
			public static By byClickOKButtonXpath                 = By.xpath("(//div[@class='cke_dialog_body']//span[text()='OK'])[2]");
			public static By byScrollToBasicInfoXpath             = By.xpath("//span[text()='Basic Info']");
			public static By byClickBasicInfoXpath                = By.xpath("((//span[@class='cke_bottom cke_reset_all'])[5]//preceding-sibling::*)[2]");
			public static By byClickBasicContactInfoXpath         = By.xpath("((//span[@class='cke_bottom cke_reset_all'])[6]//preceding-sibling::*)[2]");
			public static By byScrollToStepsXpath                 = By.xpath("//span[text()='Steps']");
			public static By byClickStepsXpath                    = By.xpath("((//span[@class='cke_bottom cke_reset_all'])[7]//preceding-sibling::*)[2]");
			public static By byClickStepsContactInfoXpath         = By.xpath("((//span[@class='cke_bottom cke_reset_all'])[8]//preceding-sibling::*)[2]");
			public static By byScrollToFormsandResourcesXpath     = By.xpath("//span[text()='Forms & Resources']");
			public static By byClickFormsAndResourceXpath         = By.xpath("((//span[@class='cke_bottom cke_reset_all'])[9]//preceding-sibling::*)[2]");
			public static By byClickFormsResourceContactInfoXpath = By.xpath("((//span[@class='cke_bottom cke_reset_all'])[10]//preceding-sibling::*)[2]");
			public static By byScrollToSalesConnectionsXpath      = By.xpath("//span[text()='Sales Connections']");
			public static By byClickSalesConnectionsXpath         = By.xpath("((//span[@class='cke_bottom cke_reset_all'])[11]//preceding-sibling::*)[2]");
			public static By byClickSalesConnectionsInfoXpath     = By.xpath("((//span[@class='cke_bottom cke_reset_all'])[12]//preceding-sibling::*)[2]");
			public static By byScrollToAnswerTypeXpath            = By.xpath("//span[text()='Answer Type']");
			public static By byClickAnswerTypesXpath              = By.xpath("((//span[@class='cke_bottom cke_reset_all'])[13]//preceding-sibling::*)[2]");
			public static By byScrollToAddAnsXpath                = By.xpath("//input[@value='Add Answer Type']");
			public static By byScrollToContentBasicXpath          = By.xpath("(//span[text()='Content'])[3]");
			public static By byScrollToContentStepsXpath          = By.xpath("(//span[text()='Content'])[4]");
			public static By byScrollToContentFormsAnsResourceXpath = By.xpath("(//span[text()='Content'])[5]");
			public static By byScrollToContentSalesXpath          = By.xpath("(//span[text()='Content'])[6]");
			public static By byScrollToFileAttachmentXpath        = By.xpath("//span[text()='File Attachment']");
			public static By byScrollToTeamsXpath                 = By.xpath("//span[text()='Teams']");
			public static By byClickTeamSelectionXpath            = By.xpath("//span[text()='Teams']//following::select//option[text()='Accounting & Finance']");
			public static By byClickComplianceCheckBoxXpath       = By.xpath("//span[text()='Compliance']//preceding-sibling::input");		
			public static By byClickNeedToKnowRadioNOXpath        = By.xpath("//span[text()='No ']//preceding-sibling::input");
			public static By byScrollNeedtoKnowImagesXpath        = By.xpath("//span[text()='Need to Know Images']");
			public static By byClickMajorChangeXpath              = By.xpath("//span[text()='Major Change']//preceding-sibling::input");
			public static By byClickCorporateSelectionXpath       = By.xpath("//span[text()='Corporate/Branch/Service Center']//following::select//option[text()='Service Center']");
			public static By byClickDepartmentSelectionXpath      = By.xpath("//span[text()='Department']//following::select//option[text()='0004 SEG Development Team']");
			public static By byClickManagerLevelSelectionXpath    = By.xpath("//span[text()='Manager Level']//following::select//option[text()='Assistant Manager']");
			public static By byClickEmployeeSelectionXpath        = By.xpath("//span[contains(text(),'time with')]//following::select//option[contains(text(),'1 Month ')]");
			public static By byClickBranchNameSelectionXpath      = By.xpath("//span[contains(text(),'Branch Name')]//following::select//option[contains(text(),'Albuquerque - Golf Course Road Branch')]");
			public static By byClickBranchAreaSelectionXpath      = By.xpath("//span[contains(text(),'Branch Area')]//following::select//option[contains(text(),'Teton')]");
			public static By byClickPrimaryTagSelectionXpath      = By.xpath("(//span[contains(text(),'Primary Tag')]//following::select//option[contains(text(),'AAA')])[1]");
			public static By byClickSecondaryTagSelectionXpath    = By.xpath("(//span[contains(text(),'Primary Tag')]//following::select//option[contains(text(),'AAA')])[4]");
			public static By byClickTertiaryTagSelectionXpath     = By.xpath("(//span[contains(text(),'Primary Tag')]//following::select//option[contains(text(),'AAA')])[6]");
			//public static By byClickRepositoryPlusbuttonXpath     = By.xpath("(//td[text()='�Repository View Selection ']//following::a)[1]");
			public static By byClickRepositoryPlusbuttonXpath     = By.xpath("//input[@testidentifier='ContentAttributes_RepoViewSelection']");
			public static By byClickRepositorySelectionbuttonXpath = By.xpath("(//td[text()='�Repository View Selection ']//following::input)[1]");
			public static By byClickIframeXpath                   = By.xpath("(//iframe[contains(@src,'/macu__tstInfoManager/WebObjects/InfoManage')])[2]");
			public static By byClickCategorySelctionTypeXpath     = By.xpath("(//option[text()='Navigate']//parent::select)");
			//public static By byClickCategoryListXpath             = By.xpath("//div[@id='AVAIL']//tr//td//span[text()='Accounts']");
			public static By byClickCategoryListPlusXpath         = By.xpath("//div[@id='AVAIL']//tr//td//span[contains(text(),'AAA')]");
			public static By byClickCategoryListXpath             = By.xpath("//div[@id='AVAIL']//tr//td//span[text()='Member Connect']");
			public static By byClickCategorySubListXpath          = By.xpath("//div[@id='AVAIL']//tr//td//span[text()='New Account Framework']");
			public static By byClickCategoryAddButtonXpath        = By.xpath("//a[text()='Add']");
			public static By byClickCategoryTopLevelXpath         = By.xpath("(//span[text()='Top Level'])[1]");
			public static By byClickProductTopLevelXpath          = By.xpath("//strong[text()='Business Accounts']");
			public static By byClickProductDropDownXpath          = By.xpath("//select[@class='dropdown']");
			public static By bySelectProductDropDownSearchXpath   = By.xpath("//select[@class='dropdown']//option[text()='Search']");
			public static By bySelectProductsearchstringXpath     = By.xpath("//input[@value='Enter search string']");
			public static By bySelectUserGroupXpath               = By.xpath("//span[text()='Asset Management']");
			public static By byScrollPublishingOptionsXpath       = By.xpath("//span[text()='Display On']");
			public static By byDisplayDateXpath                   = By.xpath("(//img[@class='ui-datepicker-trigger'])[6]");
			public static By byRemoveDateXpath                    = By.xpath("(//img[@class='ui-datepicker-trigger'])[7]");
			public static By byReviewDateXpath                    = By.xpath("(//img[@class='ui-datepicker-trigger'])[8]");
			public static By bystartTimeEditXpath                 = By.xpath("//input[@name='startTimeEdit']");
			public static By byendTimeEditXpath                   = By.xpath("//input[@name='endTimeEdit']");
			public static By byreviewTimeEditXpath                = By.xpath("//input[@name='reviewTimeEdit']");
			public static By byClickReviewDateEdiPMXpath          = By.xpath("(//select[contains(@name,'ContentEditPageWrapper')])[12]");
			public static By bySelectReviewDateEditPMXpath        = By.xpath("(//option[text()='PM'])[2]");
			public static By byReviewTimeEditPMXpath              = By.xpath("(//select[contains(@name,'ContentEditPageWrapper')])[13]");
			public static By byReviewDateEditPMXpath              = By.xpath("(//option[text()='PM'])[3]");
			public static By byNotifySubscribersXpath             = By.xpath("//input[@name='notifySubscribers']");		
			public static By bySaveDocumentXpath                  = By.xpath("//a[text()='Save Document']");
			public static By byClickArticleXpath                  = By.xpath("//a[contains(text(),'Latest COVID-19')]");
			public static By byScrollToWorkFlowXpath              = By.xpath("(//span[text()='Workflow'])");
			public static By byClickUnassignedXpath               = By.xpath("(//a[text()='Unassigned'])");
			public static By byClickAssignTaskXpath               = By.xpath("//a[text()='Assign Task']");
			public static By byScrollsectiontitleXpath            = By.xpath("//td[@class='sectiontitle']");
			public static By byClicksectiontitleXpath             = By.xpath("(//select[@class='dropdown'])[1]");		
			public static By bySelectAdministratorXpath           = By.xpath("//select[@class='dropdown']//option[text()='- Administrator']");
			public static By byClickAssignTasksXpath              = By.xpath("//a[text()='Assign Tasks']");
			public static By byClicksectionfilterXpath            = By.xpath("(//div[@class='sectionfilter']//select)[1]");
			public static By bySelectAdministratorTaskXpath       = By.xpath("(//div[@class='sectionfilter']//select)[1]//option[text()='- Administrator']");
			public static By byClickApproveXpath                  = By.xpath("//a[text()='Approve']");
			public static By byClosedApproveXpath                 = By.xpath("//span[text()='Closed']");
			public static By byScrollTOTaskDetailsXpath           = By.xpath("(//span[text()='Task Details'])[1]");
			public static By byReviewXpath                        = By.xpath("//span[text()='Review']");
			public static By byScrollToAddcommentOnlyXpath        = By.xpath("//a[text()='Add comment Only']");
			public static By byVersionXpath                       = By.xpath("//div[@class='sbmodule']//div[@class='sbmodulebody']//span[text()='Version']");
			public static By byVersionLiveXpath                   = By.xpath("(//div[@class='sbmodule']//div[@class='sbmodulebody']//span[text()='Version'])[2]");
			public static By byClickListArticleButtonXpath        = By.xpath("//div[text()='Process']//following-sibling::a[@testidentifier='ContentNavBar_List_Process']");
			public static By byClickAllDocumentsXpath             = By.xpath("//select[@testidentifier='ContentSearchResults_DocumentClassPulldown']");
			public static By bySelectAllDocumentsXpath            = By.xpath("//select[@testidentifier='ContentSearchResults_DocumentClassPulldown']//option[text()='All Documents']");
			public static By bySelectArticleXpath                 = By.xpath("(//a[text()='Latest COVID-19 Updates'])[1]");
			public static By byClickEditDocumentXpath             = By.xpath("//a[text()='Edit Document']");
			public static By byClickEditReasonXpath               = By.xpath("//textarea[@class='editfields']");
			public static By byClickSaveandContinueEditingXpath   = By.xpath("//a[text()='Save and Continue Editing']");
		    public static By byClickDoneButtonXpath               = By.xpath("(//a[text()='Done'])[1]");
		    public static By byReportingCloseXpath                = By.xpath("//a[@class='closeButton']");
			public static By byClickSearchBoxXpath                = By.xpath("(//input[@class='select-box-input'])[1]");
			public static By byClickCloseButtonXpath              = By.xpath("//a[@class='closeButton']//i[@class='fa fa-times fa-fw']");
			public static By byGettheDocumentIDXpath              = By.xpath("(//div[@class='sbmodule']//div[@class='sbmodulebody']//td//span[text()='Answer ID']/following::span)[1]");
			public static By byGettheTitleXpath                   = By.xpath("(//div[@class='imcontentcomponent']//table//div//div//div[@class='leftHardAlignment']//span)[1]");

// Sign Out, close Browser
			public static By byClickUserProfileXpath              = By.xpath("//body//oj-avatar[@initials='[[userMenuLabel]]']");
			public static By byClickUserProfileSignOutXpath       = By.xpath("//a//span[text()='Sign Out']");
		}