#==============================================================================================#
# This is file has all the configuration settings for running a Customer Portal test suite     #
# YAML file is used to store Web Elements of a web Page [User can directly pass data from here]# 
#==============================================================================================#

# This below parameter decides in which browser to run the test suite #

#browser: FIREFOX
browser: CHROME
#browser: MSEDGEDRIVER

# This below parameter decides the wait Time in seconds #
webdriverWaitTime: 100

# This below parameter decides Environment URL #
#BUI
#urlforbui: https://macu1--upgrade.custhelp.com/AgentWeb/
urlforbui: https://macu1--tst1.custhelp.com/AgentWeb/

#SignIn Credentials

buiusername: automation_testing
buipassword: Welcome123

replayforFeedBack: 'It is working as per Expected'
loginID: 'V1002'

thumbsDownComments: Flexible Work - ThumbDown Comments
feedbackReportSendDate : '09/10/2021'

#--- Swamy---
#-- Create Article
title: TestingArticle
keywords: Criticals
EditTitle: TestingArticle - Edited
Editkeywords: Criticals - Edited
contentinfo: contentinfo 'Reach out to your immediate supervisor with questions.' 
content: 'COVID-19 Update:  Find additional information on COVID-19 Branch & Service Center Operations\n
* Vaccine\n
* Similar to the flu shot, we encourage you to take a lunch hour or go after work if you choose to receive the vaccine.\n
* You should be able to easily schedule a time to receive a vaccine.
* Take PTO if an adverse reaction occurs.
* Take PTO if an adverse reaction occurs
* First URL of the pageArticle Link
* Second URL of the page
* Third URL of the page
* The few documented cases of a stronger reaction indicate that the affects typically last one to two days.
* Have an open conversation with your manager if other accommodations are necessary.
* The cost of the vaccine is covered by insurance.
* Mask Mandates
* As the counties and health departments begin to relax their mask mandates, MACU will address this as follows:
* The mask mandate requirement for team members will remain in place for the foreseeable future.
* Mask guidance for members will follow State, County and Health department guidelines for those areas.
* Personal Protection Equipment (PPE)
* Order masks and other PArticle LinkPE by submitting a ServiceNow Facilities ticket.
* Items available
* Cotopaxi masks ($7 each)
* Hand sanitizer
* Gloves
* Disposable masks
* Sanitation wipes
* Employee Resources
* Mountain America is here for you! Check out these resources:
* MACU Desktop Citrix ReceiverWorkspace Step-by-Step Surface Devices Step-by-Step
* Microsoft Teams Step-by-Step
* Multi-Factor Authentication (MFA) Step-by-Step
* Remote Work Agreement  
* Setting up Your New Laptop
* Surface Devices Step-by-Step'

Id: '1000124'
Link: 'Article Link'
BasicInfo: 'BasicInfo - Remote Work
* -Use the following resources when connecting to work applications remotely'
BasicContactInfo: 'BasicContactInfo -Remote Work
* -Use the following resources when connecting to work applications remotely
* -Cisco Finesse Step-by-Step
* -Cisco Jabber Step-by-Step  
* -Electronic Communication and Information Basic Info
* -Extend Surface Device Battery Life Step-by-Step
* -MACU Desktop Citrix ReceiverWorkspace Step-by-Step Surface Devices Step-by-Step
* -Microsoft Teams Step-by-Step
* -Multi-Factor Authentication (MFA) Step-by-Step
* -Remote Work Agreement  
* -Setting up Your New Laptop
* -Surface Devices Step-by-Step'
Steps: 'Steps- Employee Resources'
StepsContactInfo: 'StepsContactInfo - Mountain America is here for you! Check out these resources:
* Report COVID-19 in the Workplace
* Contact Tracing for COVID-19
* COVID-19 Pay Options
* Corporate FSR  
* Employee Assistance Program (EAP)
* Employee Loans
* Infectious Disease
* MACU Facility Standards
* Mountain America Center Meetings & Events
* Medical Leave of Absence
* Personal Time Off (PTO)
* Tanner Meetings & Events
* Thrive Clinic
* The CareATC Patient Access Center is currently performing all appointment scheduling activities. Our clinics are not currently accepting walk-in or self-scheduled patients. To schedule an appointment, contact the clinic 800-993-8244.
* Thrive Fitness Centers
* Travel Pay
*Traveling Branch Employees'
Forms_Resources: 'Forms_Resources - Mask Mandates'
Forms_Resources_Content: 'Forms_Resources_Content- As the counties and health departments begin to relax their mask mandates, MACU will address this as follows:
* The mask mandate requirement for team members will remain in place for the foreseeable future.
* Mask guidance for members will follow State, County and Health department guidelines for those areas.'
SalesConnections: 'SalesConnections-Sales Connections'
SalesConnectionsContent: 'SalesConnectionsContent- As the counties and health departments begin to relax their mask mandates, MACU will address this as follows:
* The mask mandate requirement for team members will remain in place for the foreseeable future.
* Mask guidance for members will follow State, County and Health department guidelines for those areas.'
AnswerType: 'https://macu1--tst.custhelp.com/app/answers/macu_view/a_id/1000124'

# Modify Article Class
EditReason: Some Important Updates
EditTitle: TestingArticle - Edited
Editkeywords: Criticals - Edited

#CallOut's

addSummary: Test Technology through Automation 10
addKeyword: Automation Technology Test 3

callouts: '<h1>Basic Info</h1>

*<h2>Rescue Loan Qualification</h2>

*<p>For a loan to qualify as rescued you must be able to say YES to EACH of the requirements below:</p>

*<ol>
 *              <li>This is a new loan to MACU</li>
 *              <li>This loan is paying off an existing loan from another financial institution (personally&nbsp;held debt and collections are not eligible)</li> 
 *              <li>I proactively rescued this loan</li>
 *              <li>I reviewed a Value Analyzer with the member and discussed how the new rescue loan meets their needs</li>
*</ol>
*<h2>Rescued Loan Incentive</h2>

*<ul>
 *              <li>MSRs and Service Center Agents will receive $10.00 plus&nbsp;$0.50 per $1,000 of rescued volume ($100 cap) for a rescue referral sent to a loan-trained employee (FSR, Outbound Agent, etc.)</li>
     *          <li>Loan-trained team members who originate and book a rescued loan will receive&nbsp;$2 per $1,000 of rescued volume&nbsp;($100 cap).
   *            <ul>
    *                        <li>When booked as a result of a referral, the incentive for the loan-trained individual changes to $1.50 per $1,000 of rescued volume.</li>
  *             </ul>
 *              </li>
*</ul>

*<div class="panel panel-default panel_note">
*<div class="panel-heading">
*<h2 class="panel-title"> 
*<span class="rn_note"><strong>Note: </strong> Need to rename a multi-workspace channel on an Enterprise Grid org? Only the Owners or Admins of the workspace or org can do so.</span>
*</h2>
*</div>
*</div>

*<div class="panel panel-default panel_tip">
*<div class="panel-heading">
*<h2 class="panel-title"> 
*<span class="rn_tip"><strong>Tip:</strong> Only the Owners or Admins of the org can edit this content.</span>
*</h2>
*</div>
*</div>

*<div class="panel panel-default panel_updated">
*<div class="panel-heading">
*<h2 class="panel-title"> 
*<span class="rn_updated"><strong>COVID-19 Update: </strong> Qualifications to Open and Make Contributions</span>
*</h2>
*</div>
*</div>

*<div class="panel panel-default panel_video">
*<div class="panel-heading">
*<h2 class="panel-title">
*<a class="collapsed" data-toggle="collapse" href="#panel_video_bodyone"> 
*<span class="rn_video">Video Title</span></a></h2>
*</div>
*<div aria-expanded="true" class="panel-collapse collapse " id="panel_video_bodyone" role="tabpanel">&nbsp;
*<div class="col-sm-12">
*<iframe allowfullscreen="" frameborder="0" height="auto" scrolling="no" src="https://web.microsoftstream.com/embed/video/e865da0e-1116-4ada-b64e-230d0807e343?autoplay=false&amp;showinfo=true" style="border: currentColor; border-image: none;" width="100%"></iframe></div>
*</div>
*</div>'